import { Word, Category } from './types';

const today = new Date().toISOString().split('T')[0];

const makeWord = (id: number, english: string, hebrew: string, category: Category, example: string): Word => ({
  id: `w${id}`,
  english,
  hebrew,
  category,
  interval: 0,
  nextReview: today,
  timesCorrect: 0,
  state: 'new',
  example,
});

export const seedWords: Word[] = [
  // core_academic (40)
  makeWord(1, 'Hypothesis', 'השערה', 'core_academic', 'We need to test our hypothesis before presenting the findings.'),
  makeWord(2, 'Methodology', 'מתודולוגיה', 'core_academic', 'The research methodology was approved by the committee.'),
  makeWord(3, 'Paradigm', 'פרדיגמה', 'core_academic', 'This represents a paradigm shift in our understanding.'),
  makeWord(4, 'Empirical', 'אמפירי', 'core_academic', 'We rely on empirical evidence to support our claims.'),
  makeWord(5, 'Synthesis', 'סינתזה', 'core_academic', 'The paper offers a synthesis of current research.'),
  makeWord(6, 'Discourse', 'שיח', 'core_academic', 'The political discourse has shifted dramatically.'),
  makeWord(7, 'Inference', 'הסקה', 'core_academic', 'We can draw an inference from the available data.'),
  makeWord(8, 'Threshold', 'סף', 'core_academic', 'The results exceeded the statistical threshold.'),
  makeWord(9, 'Correlation', 'מתאם', 'core_academic', 'There is a strong correlation between the two variables.'),
  makeWord(10, 'Abstract', 'תקציר', 'core_academic', 'Please submit an abstract for the conference.'),
  makeWord(51, 'Rationale', 'נימוק', 'core_academic', 'The rationale behind this decision is clearly documented.'),
  makeWord(52, 'Criterion', 'קריטריון', 'core_academic', 'Cost is the primary criterion for selection.'),
  makeWord(53, 'Benchmark', 'אמת מידה', 'core_academic', 'We use industry benchmarks to evaluate performance.'),
  makeWord(54, 'Implication', 'השלכה', 'core_academic', 'The implications of this finding are significant.'),
  makeWord(55, 'Assumption', 'הנחה', 'core_academic', 'We need to revisit our core assumptions.'),
  makeWord(56, 'Validation', 'אימות', 'core_academic', 'Validation of the model requires additional data.'),
  makeWord(57, 'Scope', 'היקף', 'core_academic', 'The scope of the study was limited to urban areas.'),
  makeWord(58, 'Outcome', 'תוצאה', 'core_academic', 'The expected outcome was clearly defined.'),
  makeWord(59, 'Variable', 'משתנה', 'core_academic', 'We identified three key variables in the experiment.'),
  makeWord(60, 'Insight', 'תובנה', 'core_academic', 'The data provided valuable insights into user behavior.'),
  makeWord(61, 'Framework', 'מסגרת', 'core_academic', 'We developed a conceptual framework for the analysis.'),
  makeWord(62, 'Narrative', 'נרטיב', 'core_academic', 'The official narrative does not match the evidence.'),
  makeWord(63, 'Mechanism', 'מנגנון', 'core_academic', 'The mechanism behind this process is not fully understood.'),
  makeWord(64, 'Rationale', 'הנמקה', 'core_academic', 'Please provide a clear rationale for this recommendation.'),
  makeWord(65, 'Taxonomy', 'טקסונומיה', 'core_academic', 'We created a taxonomy to classify the findings.'),
  makeWord(66, 'Iteration', 'חזרתיות', 'core_academic', 'The iterative process led to continuous improvement.'),
  makeWord(67, 'Precursor', 'קודמן', 'core_academic', 'This event was a precursor to the major policy change.'),
  makeWord(68, 'Aggregate', 'מצטבר', 'core_academic', 'The aggregate data shows a clear trend.'),
  makeWord(69, 'Causality', 'סיבתיות', 'core_academic', 'We cannot establish causality from this data alone.'),
  makeWord(70, 'Conceptual', 'רעיוני', 'core_academic', 'The conceptual model guides our research design.'),
  makeWord(71, 'Evaluate', 'להעריך', 'core_academic', 'We need to evaluate all available options.'),
  makeWord(72, 'Quantitative', 'כמותי', 'core_academic', 'The quantitative analysis confirms our hypothesis.'),
  makeWord(73, 'Qualitative', 'איכותני', 'core_academic', 'Qualitative research reveals patterns in human behavior.'),
  makeWord(74, 'Coherent', 'קוהרנטי', 'core_academic', 'The argument must be coherent and well-structured.'),
  makeWord(75, 'Relevant', 'רלוונטי', 'core_academic', 'Only relevant data should be included in the report.'),
  makeWord(76, 'Robust', 'חסון', 'core_academic', 'The methodology must be robust and repeatable.'),
  makeWord(77, 'Preliminary', 'מקדמי', 'core_academic', 'These are preliminary findings pending final review.'),
  makeWord(78, 'Contextual', 'הקשרי', 'core_academic', 'Contextual factors must be considered in the analysis.'),
  makeWord(79, 'Ratify', 'לאשרר', 'core_academic', 'The board needs to ratify this decision.'),
  makeWord(80, 'Assess', 'לאמוד', 'core_academic', 'We must assess the risks before proceeding.'),

  // ai_tech (40)
  makeWord(11, 'Algorithm', 'אלגוריתם', 'ai_tech', 'The algorithm processes data in real time.'),
  makeWord(12, 'Neural Network', 'רשת נוירונית', 'ai_tech', 'The neural network was trained on millions of examples.'),
  makeWord(13, 'Deployment', 'פריסה', 'ai_tech', 'The deployment pipeline is fully automated.'),
  makeWord(14, 'Scalability', 'מדרגיות', 'ai_tech', 'Scalability is a key concern for this architecture.'),
  makeWord(15, 'Latency', 'השהיה', 'ai_tech', 'We reduced API latency by 40 percent.'),
  makeWord(16, 'Iteration', 'איטרציה', 'ai_tech', 'Each iteration improves the model accuracy.'),
  makeWord(17, 'Bias', 'הטיה', 'ai_tech', 'We must address bias in the training data.'),
  makeWord(18, 'Benchmark', 'מדד ייחוס', 'ai_tech', 'The model outperformed existing benchmarks.'),
  makeWord(19, 'Framework', 'מסגרת עבודה', 'ai_tech', 'We adopted a new machine learning framework.'),
  makeWord(20, 'Token', 'טוקן', 'ai_tech', 'The model processes text as a sequence of tokens.'),
  makeWord(81, 'Inference', 'הסקת מסקנות', 'ai_tech', 'Model inference speed is critical for real-time applications.'),
  makeWord(82, 'Fine-tuning', 'כיוון עדין', 'ai_tech', 'Fine-tuning the model improved accuracy by 15 percent.'),
  makeWord(83, 'Prompt', 'פרומפט', 'ai_tech', 'Crafting a clear prompt leads to better AI outputs.'),
  makeWord(84, 'Hallucination', 'הזיה', 'ai_tech', 'AI hallucination is a known risk in language models.'),
  makeWord(85, 'Embedding', 'הטמעה', 'ai_tech', 'Word embeddings capture semantic meaning.'),
  makeWord(86, 'Pipeline', 'צינור עיבוד', 'ai_tech', 'The data pipeline processes millions of records daily.'),
  makeWord(87, 'Overfitting', 'התאמת יתר', 'ai_tech', 'Overfitting occurs when a model learns noise in the training data.'),
  makeWord(88, 'Annotation', 'תיוג', 'ai_tech', 'Data annotation is time-consuming but essential.'),
  makeWord(89, 'Retrieval', 'אחזור', 'ai_tech', 'Retrieval-augmented generation improves factual accuracy.'),
  makeWord(90, 'Vector', 'וקטור', 'ai_tech', 'Vector search enables semantic similarity queries.'),
  makeWord(91, 'Multimodal', 'מולטי-מודאלי', 'ai_tech', 'Multimodal models process both text and images.'),
  makeWord(92, 'Context Window', 'חלון הקשר', 'ai_tech', 'A larger context window allows processing longer documents.'),
  makeWord(93, 'Generative', 'גנרטיבי', 'ai_tech', 'Generative AI can produce original content.'),
  makeWord(94, 'API', 'ממשק תכנות', 'ai_tech', 'The API allows external systems to access our service.'),
  makeWord(95, 'Automation', 'אוטומציה', 'ai_tech', 'Automation reduces manual workload significantly.'),
  makeWord(96, 'Integration', 'אינטגרציה', 'ai_tech', 'The integration with existing systems went smoothly.'),
  makeWord(97, 'Dataset', 'מאגר נתונים', 'ai_tech', 'A diverse dataset improves model generalization.'),
  makeWord(98, 'Accuracy', 'דיוק', 'ai_tech', 'Model accuracy reached 97 percent on the test set.'),
  makeWord(99, 'Threshold', 'סף', 'ai_tech', 'We set a confidence threshold of 0.85 for predictions.'),
  makeWord(100, 'Architecture', 'ארכיטקטורה', 'ai_tech', 'The transformer architecture revolutionized NLP.'),
  makeWord(101, 'Cache', 'מטמון', 'ai_tech', 'Caching frequent responses reduces API costs.'),
  makeWord(102, 'Cluster', 'אשכול', 'ai_tech', 'The data naturally clusters into three groups.'),
  makeWord(103, 'Feature', 'תכונה', 'ai_tech', 'Feature engineering significantly improves model performance.'),
  makeWord(104, 'Output', 'פלט', 'ai_tech', 'The model output must be validated before use.'),
  makeWord(105, 'Prediction', 'תחזית', 'ai_tech', 'The model prediction was accurate 9 out of 10 times.'),
  makeWord(106, 'Synthetic', 'סינתטי', 'ai_tech', 'Synthetic data was generated to supplement real examples.'),
  makeWord(107, 'Version', 'גרסה', 'ai_tech', 'Always document the model version used in production.'),
  makeWord(108, 'Workflow', 'תהליך עבודה', 'ai_tech', 'The AI workflow automates document classification.'),
  makeWord(109, 'Zero-shot', 'אפס-זריקות', 'ai_tech', 'Zero-shot learning allows the model to handle unseen tasks.'),
  makeWord(110, 'Evaluation', 'הערכה', 'ai_tech', 'Rigorous evaluation is essential before model deployment.'),

  // government_policy (40)
  makeWord(21, 'Regulation', 'רגולציה', 'government_policy', 'New regulation requires full compliance by Q3.'),
  makeWord(22, 'Legislation', 'חקיקה', 'government_policy', 'The legislation was passed unanimously.'),
  makeWord(23, 'Jurisdiction', 'סמכות שיפוט', 'government_policy', 'This falls outside our jurisdiction.'),
  makeWord(24, 'Amendment', 'תיקון', 'government_policy', 'The amendment addresses privacy concerns.'),
  makeWord(25, 'Compliance', 'ציות', 'government_policy', 'Compliance with GDPR is mandatory.'),
  makeWord(26, 'Bureaucracy', 'בירוקרטיה', 'government_policy', 'The bureaucracy slows down innovation.'),
  makeWord(27, 'Mandate', 'מנדט', 'government_policy', 'The government issued a new mandate.'),
  makeWord(28, 'Transparency', 'שקיפות', 'government_policy', 'Transparency is essential for public trust.'),
  makeWord(29, 'Accountability', 'אחריותיות', 'government_policy', 'We need greater accountability in public spending.'),
  makeWord(30, 'Stakeholder', 'בעל עניין', 'government_policy', 'All stakeholders were consulted during the process.'),
  makeWord(111, 'Procurement', 'רכש', 'government_policy', 'The procurement process must follow government guidelines.'),
  makeWord(112, 'Oversight', 'פיקוח', 'government_policy', 'Parliamentary oversight ensures government accountability.'),
  makeWord(113, 'Directive', 'הנחיה', 'government_policy', 'The ministry issued a directive on data handling.'),
  makeWord(114, 'Governance', 'ממשל', 'government_policy', 'Good governance requires clear processes and transparency.'),
  makeWord(115, 'Policy', 'מדיניות', 'government_policy', 'The new policy takes effect at the start of next year.'),
  makeWord(116, 'Initiative', 'יוזמה', 'government_policy', 'The digital transformation initiative spans five years.'),
  makeWord(117, 'Reform', 'רפורמה', 'government_policy', 'Structural reform is needed to improve efficiency.'),
  makeWord(118, 'Authority', 'רשות', 'government_policy', 'The regulatory authority approved the new standard.'),
  makeWord(119, 'Protocol', 'פרוטוקול', 'government_policy', 'All meetings must follow the official protocol.'),
  makeWord(120, 'Audit', 'ביקורת', 'government_policy', 'An independent audit was commissioned by the minister.'),
  makeWord(121, 'Tender', 'מכרז', 'government_policy', 'The tender was awarded to the lowest bidder.'),
  makeWord(122, 'Resolution', 'החלטה', 'government_policy', 'The resolution was adopted with a majority vote.'),
  makeWord(123, 'Enforcement', 'אכיפה', 'government_policy', 'Enforcement of the new rules begins in January.'),
  makeWord(124, 'Subsidiary', 'גוף משנה', 'government_policy', 'A subsidiary body was established to handle appeals.'),
  makeWord(125, 'Allocation', 'הקצאה', 'government_policy', 'Budget allocation must reflect strategic priorities.'),
  makeWord(126, 'Interoperability', 'יכולת פעולה הדדית', 'government_policy', 'Interoperability between government systems is critical.'),
  makeWord(127, 'Public sector', 'מגזר ציבורי', 'government_policy', 'Public sector innovation requires political will.'),
  makeWord(128, 'Obligation', 'חובה', 'government_policy', 'There is a legal obligation to disclose this information.'),
  makeWord(129, 'Criterion', 'אמת מידה', 'government_policy', 'The eligibility criterion was revised last month.'),
  makeWord(130, 'Inquiry', 'חקירה', 'government_policy', 'A formal inquiry was launched into the incident.'),
  makeWord(131, 'Benchmark', 'ספסל ציון', 'government_policy', 'International benchmarks guide our performance targets.'),
  makeWord(132, 'Coalition', 'קואליציה', 'government_policy', 'The coalition agreement included digital transformation goals.'),
  makeWord(133, 'Consultation', 'היוועצות', 'government_policy', 'Public consultation is required before the policy changes.'),
  makeWord(134, 'Empowerment', 'העצמה', 'government_policy', 'Digital empowerment of citizens is a key goal.'),
  makeWord(135, 'Fiscal', 'פיסקלי', 'government_policy', 'Fiscal responsibility is central to government policy.'),
  makeWord(136, 'Ministerial', 'שרי', 'government_policy', 'Ministerial approval is required for budget changes.'),
  makeWord(137, 'Sanctions', 'סנקציות', 'government_policy', 'Sanctions were imposed for non-compliance.'),
  makeWord(138, 'Sovereignty', 'ריבונות', 'government_policy', 'Data sovereignty is a growing concern for governments.'),
  makeWord(139, 'Strategic', 'אסטרטגי', 'government_policy', 'A strategic plan was developed for the next five years.'),
  makeWord(140, 'Welfare', 'רווחה', 'government_policy', 'Social welfare programs support vulnerable populations.'),

  // meeting_communication (40)
  makeWord(31, 'Agenda', 'סדר יום', 'meeting_communication', 'Let me share the agenda for today\'s meeting.'),
  makeWord(32, 'Consensus', 'קונצנזוס', 'meeting_communication', 'We reached a consensus on the budget allocation.'),
  makeWord(33, 'Delegate', 'להאציל', 'meeting_communication', 'I\'ll delegate this task to the project lead.'),
  makeWord(34, 'Facilitate', 'לנהל/להקל', 'meeting_communication', 'She will facilitate the workshop next week.'),
  makeWord(35, 'Elaborate', 'להרחיב', 'meeting_communication', 'Could you elaborate on your proposal?'),
  makeWord(36, 'Prioritize', 'לתעדף', 'meeting_communication', 'We need to prioritize the critical issues.'),
  makeWord(37, 'Feasibility', 'היתכנות', 'meeting_communication', 'The feasibility study will be ready by Monday.'),
  makeWord(38, 'Milestone', 'אבן דרך', 'meeting_communication', 'We achieved a major milestone this quarter.'),
  makeWord(39, 'Follow-up', 'מעקב', 'meeting_communication', 'I\'ll send a follow-up email after the meeting.'),
  makeWord(40, 'Deliverable', 'תוצר', 'meeting_communication', 'The final deliverable is due next Friday.'),
  makeWord(141, 'Action item', 'פריט לפעולה', 'meeting_communication', 'Each action item was assigned an owner and deadline.'),
  makeWord(142, 'Bandwidth', 'עומס עבודה', 'meeting_communication', 'Do you have the bandwidth to take on this project?'),
  makeWord(143, 'Align', 'ליישר', 'meeting_communication', 'Let\'s align on expectations before we proceed.'),
  makeWord(144, 'Escalate', 'להסלים', 'meeting_communication', 'We need to escalate this to senior management.'),
  makeWord(145, 'Leverage', 'למנף', 'meeting_communication', 'We can leverage our existing partnerships here.'),
  makeWord(146, 'Synergy', 'סינרגיה', 'meeting_communication', 'The merger created significant synergies between teams.'),
  makeWord(147, 'Takeaway', 'מסקנה', 'meeting_communication', 'The key takeaway from today\'s meeting is the new deadline.'),
  makeWord(148, 'Onboard', 'לקלוט', 'meeting_communication', 'We need to onboard the new team members quickly.'),
  makeWord(149, 'Circulate', 'להפיץ', 'meeting_communication', 'Please circulate the report before the meeting.'),
  makeWord(150, 'Chair', 'לנהל', 'meeting_communication', 'Who will chair tomorrow\'s session?'),
  makeWord(151, 'Capacity', 'כושר', 'meeting_communication', 'We don\'t have the capacity to add more tasks this sprint.'),
  makeWord(152, 'Escalation', 'הסלמה', 'meeting_communication', 'The escalation path was clearly defined in the plan.'),
  makeWord(153, 'Bottleneck', 'צוואר בקבוק', 'meeting_communication', 'Approvals are the main bottleneck in our workflow.'),
  makeWord(154, 'Handoff', 'העברה', 'meeting_communication', 'A clean handoff ensures continuity between teams.'),
  makeWord(155, 'Impact', 'השפעה', 'meeting_communication', 'What is the potential impact of this decision?'),
  makeWord(156, 'Objective', 'מטרה', 'meeting_communication', 'Each team member should understand their key objectives.'),
  makeWord(157, 'Ownership', 'בעלות', 'meeting_communication', 'Clear ownership drives accountability and results.'),
  makeWord(158, 'Proceed', 'להמשיך', 'meeting_communication', 'Can we proceed with the original plan?'),
  makeWord(159, 'Recap', 'סיכום', 'meeting_communication', 'Let me recap the key decisions from this meeting.'),
  makeWord(160, 'Risk', 'סיכון', 'meeting_communication', 'We need to identify and mitigate potential risks.'),
  makeWord(161, 'Stakeholder', 'מחזיק עניין', 'meeting_communication', 'Stakeholder buy-in is essential for success.'),
  makeWord(162, 'Streamline', 'לייעל', 'meeting_communication', 'We should streamline the approval process.'),
  makeWord(163, 'Timeline', 'לוח זמנים', 'meeting_communication', 'The project timeline was approved by all parties.'),
  makeWord(164, 'Touchpoint', 'נקודת מגע', 'meeting_communication', 'Weekly touchpoints help keep the team aligned.'),
  makeWord(165, 'Visibility', 'ראות', 'meeting_communication', 'We need better visibility into project progress.'),
  makeWord(166, 'Commit', 'להתחייב', 'meeting_communication', 'Can you commit to delivering this by Thursday?'),
  makeWord(167, 'Clarity', 'בהירות', 'meeting_communication', 'Let\'s ensure clarity on roles and responsibilities.'),
  makeWord(168, 'Proactive', 'יזמי', 'meeting_communication', 'We need to be more proactive about addressing risks.'),
  makeWord(169, 'Feedback', 'משוב', 'meeting_communication', 'Your feedback on the proposal was very helpful.'),
  makeWord(170, 'Wrap up', 'לסכם', 'meeting_communication', 'Let\'s wrap up with a summary of action items.'),

  // everyday (40)
  makeWord(41, 'Nevertheless', 'בכל זאת', 'everyday', 'Nevertheless, we decided to proceed with the plan.'),
  makeWord(42, 'Furthermore', 'יתרה מכך', 'everyday', 'Furthermore, the data supports our conclusion.'),
  makeWord(43, 'Meanwhile', 'בינתיים', 'everyday', 'Meanwhile, the team continued working on the prototype.'),
  makeWord(44, 'Approximately', 'בקירוב', 'everyday', 'The project will take approximately three months.'),
  makeWord(45, 'Comprehensive', 'מקיף', 'everyday', 'We prepared a comprehensive report for the board.'),
  makeWord(46, 'Substantial', 'משמעותי', 'everyday', 'There has been substantial progress this year.'),
  makeWord(47, 'Distinguish', 'להבחין', 'everyday', 'It\'s important to distinguish between the two approaches.'),
  makeWord(48, 'Inevitable', 'בלתי נמנע', 'everyday', 'Change is inevitable in this industry.'),
  makeWord(49, 'Prospect', 'סיכוי/תחזית', 'everyday', 'The prospect of expansion is exciting.'),
  makeWord(50, 'Subsequent', 'עוקב', 'everyday', 'Subsequent meetings will address the remaining issues.'),
  makeWord(171, 'Ultimately', 'בסופו של דבר', 'everyday', 'Ultimately, the decision rests with the director.'),
  makeWord(172, 'Apparently', 'כנראה', 'everyday', 'Apparently, the budget was not approved in time.'),
  makeWord(173, 'Consequently', 'כתוצאה מכך', 'everyday', 'Consequently, the launch was delayed by two weeks.'),
  makeWord(174, 'Nonetheless', 'אף על פי כן', 'everyday', 'Nonetheless, the team delivered impressive results.'),
  makeWord(175, 'Primarily', 'בעיקר', 'everyday', 'The issue is primarily one of resource allocation.'),
  makeWord(176, 'Specifically', 'באופן ספציפי', 'everyday', 'Specifically, we need to address the security vulnerabilities.'),
  makeWord(177, 'Significantly', 'באופן משמעותי', 'everyday', 'Costs were significantly reduced this quarter.'),
  makeWord(178, 'Essentially', 'בעיקרו של דבר', 'everyday', 'Essentially, this is a resource problem.'),
  makeWord(179, 'Typically', 'בדרך כלל', 'everyday', 'Typically, the process takes about two weeks.'),
  makeWord(180, 'Initially', 'בתחילה', 'everyday', 'Initially, the plan was met with resistance.'),
  makeWord(181, 'Presumably', 'על פי ההנחה', 'everyday', 'Presumably, the committee has reviewed the report.'),
  makeWord(182, 'Notably', 'יש לציין', 'everyday', 'Notably, the results exceeded all expectations.'),
  makeWord(183, 'Accordingly', 'בהתאם לכך', 'everyday', 'Accordingly, we adjusted the project timeline.'),
  makeWord(184, 'Alternatively', 'לחלופין', 'everyday', 'Alternatively, we could outsource this component.'),
  makeWord(185, 'Remarkably', 'באופן מרשים', 'everyday', 'Remarkably, the system handled the peak load without issues.'),
  makeWord(186, 'Broadly', 'באופן רחב', 'everyday', 'Broadly speaking, the project is on track.'),
  makeWord(187, 'Precisely', 'בדיוק', 'everyday', 'This is precisely the kind of innovation we need.'),
  makeWord(188, 'Thoroughly', 'ביסודיות', 'everyday', 'The proposal was thoroughly reviewed before approval.'),
  makeWord(189, 'Explicitly', 'במפורש', 'everyday', 'The requirements were explicitly stated in the contract.'),
  makeWord(190, 'Efficiently', 'ביעילות', 'everyday', 'We need to deliver this project efficiently and on budget.'),
  makeWord(191, 'Consistently', 'בעקביות', 'everyday', 'The team consistently met its targets this year.'),
  makeWord(192, 'Effectively', 'ביעילות', 'everyday', 'We communicated the changes effectively to all teams.'),
  makeWord(193, 'Fundamentally', 'מהותית', 'everyday', 'This is fundamentally a leadership challenge.'),
  makeWord(194, 'Strategically', 'אסטרטגית', 'everyday', 'We need to think more strategically about partnerships.'),
  makeWord(195, 'Collectively', 'באופן קולקטיבי', 'everyday', 'Collectively, the team made a major contribution this year.'),
  makeWord(196, 'Apparently', 'לכאורה', 'everyday', 'Apparently the contract was signed last week.'),
  makeWord(197, 'Regardless', 'בכל מקרה', 'everyday', 'Regardless of the outcome, we must document the process.'),
  makeWord(198, 'Presumably', 'בהנחה ש', 'everyday', 'Presumably this has already been discussed with legal.'),
  makeWord(199, 'Approximately', 'כ-', 'everyday', 'Approximately 200 employees will be affected.'),
  makeWord(200, 'Conclusively', 'באופן חד-משמעי', 'everyday', 'The results conclusively support our original hypothesis.'),
];

export const professionalPhrases = [
  {
    id: 'p1',
    phrase: "I'd like to circle back on this issue.",
    hebrew: "אני רוצה לחזור לנושא הזה.",
    variations: [
      "Let's revisit this topic.",
      "I want to follow up on this matter.",
      "Can we return to this point?"
    ]
  },
  {
    id: 'p2',
    phrase: "Let's align on the key takeaways.",
    hebrew: "בואו נסנכרן על המסקנות המרכזיות.",
    variations: [
      "Let's make sure we're on the same page regarding the main points.",
      "Can we agree on the core conclusions?",
      "Let's summarize what we've agreed on."
    ]
  },
  {
    id: 'p3',
    phrase: "I'd recommend we take a data-driven approach.",
    hebrew: "אני ממליץ שניקח גישה מבוססת נתונים.",
    variations: [
      "Let's base our decision on the evidence.",
      "I suggest we look at what the numbers tell us.",
      "We should rely on data to guide this decision."
    ]
  },
  {
    id: 'p4',
    phrase: "Could you walk us through the key findings?",
    hebrew: "האם תוכל/י להציג לנו את הממצאים המרכזיים?",
    variations: [
      "Would you mind presenting the highlights?",
      "Can you summarize the main results for us?",
      "Please share the most important discoveries."
    ]
  },
  {
    id: 'p5',
    phrase: "We need to ensure cross-functional alignment.",
    hebrew: "אנחנו צריכים להבטיח תיאום בין-מחלקתי.",
    variations: [
      "All departments need to be on the same page.",
      "Let's coordinate across teams.",
      "We should sync with all relevant stakeholders."
    ]
  },
  {
    id: 'p6',
    phrase: "Let's table this discussion for now.",
    hebrew: "בואו נדחה את הדיון הזה לעת עתה.",
    variations: [
      "Let's postpone this topic to a later meeting.",
      "We can revisit this when we have more information.",
      "I suggest we park this issue for now."
    ]
  },
  {
    id: 'p7',
    phrase: "The ROI on this initiative is significant.",
    hebrew: "ההחזר על ההשקעה ביוזמה הזו משמעותי.",
    variations: [
      "This project delivers strong returns.",
      "The value generated by this initiative justifies the investment.",
      "We're seeing excellent return on this effort."
    ]
  },
  {
    id: 'p8',
    phrase: "I'd like to push back on that assumption.",
    hebrew: "אני רוצה להתנגד להנחה הזו.",
    variations: [
      "I have concerns about that premise.",
      "I'm not sure that assumption holds.",
      "I'd challenge that underlying belief."
    ]
  },
  {
    id: 'p9',
    phrase: "Let's establish clear ownership and accountability.",
    hebrew: "בואו נגדיר בעלות ואחריות ברורה.",
    variations: [
      "We need to assign clear responsibilities.",
      "Who owns this deliverable?",
      "Let's make sure each task has a clear owner."
    ]
  },
  {
    id: 'p10',
    phrase: "We should leverage our existing infrastructure.",
    hebrew: "עלינו לנצל את התשתית הקיימת שלנו.",
    variations: [
      "Let's build on what we already have.",
      "We can make better use of our current systems.",
      "There's no need to start from scratch."
    ]
  },
];
