
-- Add Rounds 5-8 with diverse content
INSERT INTO public.lessons (season, round, order_in_round, type, topic_tag, title_he, content, xp_reward, boots_reward) VALUES

-- ROUND 5: Body & Actions
(1, 5, 1, 'words', 'daily_life', 'חלקי גוף', '{"words":[{"english":"Head","hebrew":"ראש","emoji":"🗣️"},{"english":"Hand","hebrew":"יד","emoji":"✋"},{"english":"Foot","hebrew":"רגל","emoji":"🦶"},{"english":"Eye","hebrew":"עין","emoji":"👁️"},{"english":"Ear","hebrew":"אוזן","emoji":"👂"}]}'::jsonb, 60, 15),

(1, 5, 2, 'words', 'football', 'פעולות במגרש', '{"words":[{"english":"Shoot","hebrew":"בעט","emoji":"🦵"},{"english":"Jump","hebrew":"קפוץ","emoji":"🤸"},{"english":"Catch","hebrew":"תפוס","emoji":"🧤"},{"english":"Throw","hebrew":"זרוק","emoji":"🤾"},{"english":"Score","hebrew":"הבקע","emoji":"🥅"}]}'::jsonb, 60, 15),

(1, 5, 3, 'quiz', 'daily_life', 'חידון גוף ופעולות', '{"questions":[{"question":"What do you kick the ball with?","options":["Hand","Foot","Head","Ear"],"correct":1,"emoji":"⚽","explanation_he":"Foot = רגל, בועטים בכדור עם הרגל!"},{"question":"What do you see with?","options":["Ear","Hand","Eye","Foot"],"correct":2,"emoji":"👀","explanation_he":"Eye = עין, רואים עם העיניים!"},{"question":"What does the goalkeeper do?","options":["Shoot","Score","Catch","Jump"],"correct":2,"emoji":"🧤","explanation_he":"Catch = תפוס, השוער תופס את הכדור!"},{"question":"How do you say קפוץ in English?","options":["Run","Jump","Throw","Kick"],"correct":1,"emoji":"🤸","explanation_he":"Jump = קפוץ!"},{"question":"What do you hear with?","options":["Eye","Ear","Hand","Head"],"correct":1,"emoji":"👂","explanation_he":"Ear = אוזן, שומעים עם האוזניים!"}],"timer_seconds":20,"speed_bonus":true}'::jsonb, 80, 20),

(1, 5, 4, 'conversation', 'football', 'אימון עם המאמן', '{"dialogue":[{"speaker":"coach","text":"Are you ready to train?","hebrew":"אתה מוכן להתאמן?","emoji":"💪"},{"speaker":"child","hebrew":"תגיד לו שכן!","options":["Yes, I am ready!","No, thank you","Maybe later"],"correct":0},{"speaker":"coach","text":"Great! Kick the ball!","hebrew":"מעולה! בעט בכדור!","emoji":"⚽"},{"speaker":"child","hebrew":"ספר לו שבעטת חזק!","options":["I kicked it hard!","I dont know","What ball?"],"correct":0},{"speaker":"coach","text":"Amazing shot! You scored a goal!","hebrew":"בעיטה מדהימה! הבקעת שער!","emoji":"🥅"},{"speaker":"child","hebrew":"תודה למאמן!","options":["Thank you, coach!","OK bye","I want to go home"],"correct":0}]}'::jsonb, 80, 20),

-- ROUND 6: Food & Numbers
(1, 6, 1, 'words', 'daily_life', 'אוכל טעים', '{"words":[{"english":"Water","hebrew":"מים","emoji":"💧"},{"english":"Bread","hebrew":"לחם","emoji":"🍞"},{"english":"Apple","hebrew":"תפוח","emoji":"🍎"},{"english":"Banana","hebrew":"בננה","emoji":"🍌"},{"english":"Chicken","hebrew":"עוף","emoji":"🍗"}]}'::jsonb, 60, 15),

(1, 6, 2, 'letters', 'daily_life', 'אותיות K-O', '{"items":[{"letter":"K","word":"Kick","emoji":"🦵","pronunciation":"קיי"},{"letter":"L","word":"Lion","emoji":"🦁","pronunciation":"אל"},{"letter":"M","word":"Maccabi","emoji":"💛","pronunciation":"אם"},{"letter":"N","word":"Number","emoji":"🔢","pronunciation":"אן"},{"letter":"O","word":"Orange","emoji":"🍊","pronunciation":"או"}]}'::jsonb, 50, 10),

(1, 6, 3, 'quiz', 'daily_life', 'חידון אוכל ואותיות', '{"questions":[{"question":"How do you say מים in English?","options":["Milk","Water","Juice","Tea"],"correct":1,"emoji":"💧","explanation_he":"Water = מים, חשוב לשתות מים!"},{"question":"What letter does Lion start with?","options":["M","K","L","N"],"correct":2,"emoji":"🦁","explanation_he":"Lion מתחיל באות L!"},{"question":"How do you say תפוח?","options":["Banana","Orange","Apple","Bread"],"correct":2,"emoji":"🍎","explanation_he":"Apple = תפוח!"},{"question":"What letter does Maccabi start with?","options":["N","M","K","L"],"correct":1,"emoji":"💛","explanation_he":"Maccabi מתחיל באות M!"},{"question":"How do you say לחם?","options":["Bread","Water","Chicken","Apple"],"correct":0,"emoji":"🍞","explanation_he":"Bread = לחם!"}],"timer_seconds":20,"speed_bonus":true}'::jsonb, 80, 20),

(1, 6, 4, 'conversation', 'daily_life', 'הזמנת אוכל', '{"dialogue":[{"speaker":"coach","text":"Are you hungry?","hebrew":"אתה רעב?","emoji":"😋"},{"speaker":"child","hebrew":"תגיד שכן, אתה רעב!","options":["Yes, I am hungry!","No thanks","I dont know"],"correct":0},{"speaker":"coach","text":"What do you want to eat?","hebrew":"מה אתה רוצה לאכול?","emoji":"🍽️"},{"speaker":"child","hebrew":"תבקש תפוח!","options":["I want an apple, please","I want nothing","Give me everything"],"correct":0},{"speaker":"coach","text":"Here you go! Do you want water too?","hebrew":"הנה! אתה רוצה גם מים?","emoji":"🍎"},{"speaker":"child","hebrew":"תודה ובקש מים!","options":["Yes please, and thank you!","No way","I forgot"],"correct":0}]}'::jsonb, 80, 20),

-- ROUND 7: Family & Feelings
(1, 7, 1, 'words', 'daily_life', 'המשפחה שלי', '{"words":[{"english":"Mother","hebrew":"אמא","emoji":"👩"},{"english":"Father","hebrew":"אבא","emoji":"👨"},{"english":"Brother","hebrew":"אח","emoji":"👦"},{"english":"Sister","hebrew":"אחות","emoji":"👧"},{"english":"Family","hebrew":"משפחה","emoji":"👨‍👩‍👧‍👦"}]}'::jsonb, 60, 15),

(1, 7, 2, 'words', 'daily_life', 'רגשות', '{"words":[{"english":"Happy","hebrew":"שמח","emoji":"😊"},{"english":"Sad","hebrew":"עצוב","emoji":"😢"},{"english":"Excited","hebrew":"נרגש","emoji":"🤩"},{"english":"Brave","hebrew":"אמיץ","emoji":"💪"},{"english":"Proud","hebrew":"גאה","emoji":"🏆"}]}'::jsonb, 60, 15),

(1, 7, 3, 'quiz', 'daily_life', 'חידון משפחה ורגשות', '{"questions":[{"question":"How do you say אמא in English?","options":["Father","Brother","Mother","Sister"],"correct":2,"emoji":"👩","explanation_he":"Mother = אמא!"},{"question":"When you win a game, you feel...","options":["Sad","Happy","Scared","Tired"],"correct":1,"emoji":"🏆","explanation_he":"Happy = שמח! כשמנצחים שמחים!"},{"question":"How do you say אח?","options":["Sister","Father","Mother","Brother"],"correct":3,"emoji":"👦","explanation_he":"Brother = אח!"},{"question":"A hero is always...","options":["Sad","Scared","Brave","Tired"],"correct":2,"emoji":"💪","explanation_he":"Brave = אמיץ! גיבורים אמיצים!"},{"question":"How do you say גאה?","options":["Proud","Happy","Excited","Brave"],"correct":0,"emoji":"🏆","explanation_he":"Proud = גאה! תהיה גאה בעצמך!"}],"timer_seconds":20,"speed_bonus":true}'::jsonb, 80, 20),

(1, 7, 4, 'conversation', 'daily_life', 'סיפור על המשפחה', '{"dialogue":[{"speaker":"coach","text":"Tell me about your family!","hebrew":"ספר לי על המשפחה שלך!","emoji":"👨‍👩‍👧‍👦"},{"speaker":"child","hebrew":"ספר על האחים שלך!","options":["I have two brothers!","I dont have family","I forgot"],"correct":0},{"speaker":"coach","text":"Wow, thats great! Are you happy together?","hebrew":"וואו, מדהים! אתם שמחים ביחד?","emoji":"😊"},{"speaker":"child","hebrew":"תגיד שכן!","options":["Yes, we are very happy!","Sometimes","Not really"],"correct":0},{"speaker":"coach","text":"Your family must be proud of you!","hebrew":"המשפחה שלך בטח גאה בך!","emoji":"🏆"},{"speaker":"child","hebrew":"תגיד תודה!","options":["Thank you! I am proud too!","OK","Whatever"],"correct":0}]}'::jsonb, 80, 20),

-- ROUND 8: Advanced Football & Review
(1, 8, 1, 'words', 'football', 'מילים מתקדמות בכדורגל', '{"words":[{"english":"Champion","hebrew":"אלוף","emoji":"🏆"},{"english":"Stadium","hebrew":"אצטדיון","emoji":"🏟️"},{"english":"Captain","hebrew":"קפטן","emoji":"©️"},{"english":"Trophy","hebrew":"גביע","emoji":"🏆"},{"english":"Victory","hebrew":"ניצחון","emoji":"🎉"}]}'::jsonb, 70, 20),

(1, 8, 2, 'words', 'tanach', 'גיבורי התנך באנגלית', '{"words":[{"english":"Shepherd","hebrew":"רועה","emoji":"🐑"},{"english":"Prophet","hebrew":"נביא","emoji":"📜"},{"english":"Warrior","hebrew":"לוחם","emoji":"⚔️"},{"english":"Wisdom","hebrew":"חוכמה","emoji":"🧠"},{"english":"Miracle","hebrew":"נס","emoji":"✨"}]}'::jsonb, 70, 20),

(1, 8, 3, 'quiz', 'football', 'חידון סופר על הכל', '{"questions":[{"question":"The best team wins the...","options":["Ball","Stadium","Trophy","Captain"],"correct":2,"emoji":"🏆","explanation_he":"Trophy = גביע! הקבוצה הטובה ביותר מנצחת את הגביע!"},{"question":"David was a brave...","options":["Shepherd","Captain","Coach","Player"],"correct":0,"emoji":"🐑","explanation_he":"Shepherd = רועה! דוד היה רועה צאן אמיץ!"},{"question":"The leader of the team is the...","options":["Trophy","Victory","Stadium","Captain"],"correct":3,"emoji":"©️","explanation_he":"Captain = קפטן! המנהיג של הקבוצה!"},{"question":"Something amazing that happens is a...","options":["Victory","Miracle","Wisdom","Trophy"],"correct":1,"emoji":"✨","explanation_he":"Miracle = נס! כמו הניסים בתנך!"},{"question":"When you win a game, its a...","options":["Stadium","Captain","Trophy","Victory"],"correct":3,"emoji":"🎉","explanation_he":"Victory = ניצחון!"},{"question":"Solomon was known for his...","options":["Victory","Miracle","Wisdom","Trophy"],"correct":2,"emoji":"🧠","explanation_he":"Wisdom = חוכמה! שלמה המלך היה חכם מכל אדם!"}],"timer_seconds":25,"speed_bonus":true}'::jsonb, 100, 30),

(1, 8, 4, 'conversation', 'football', 'ראיון אחרי המשחק', '{"dialogue":[{"speaker":"coach","text":"Congratulations! You played amazing today!","hebrew":"מזל טוב! שיחקת מדהים היום!","emoji":"🎉"},{"speaker":"child","hebrew":"תודה למאמן!","options":["Thank you so much, coach!","OK","It was easy"],"correct":0},{"speaker":"coach","text":"How do you feel after this victory?","hebrew":"איך אתה מרגיש אחרי הניצחון?","emoji":"🏆"},{"speaker":"child","hebrew":"ספר שאתה שמח וגאה!","options":["I feel happy and proud!","I feel nothing","I want to go home"],"correct":0},{"speaker":"coach","text":"You are a true champion! Keep learning!","hebrew":"אתה אלוף אמיתי! תמשיך ללמוד!","emoji":"👑"},{"speaker":"child","hebrew":"תגיד שתמשיך ללמוד!","options":["I will keep learning every day!","Maybe tomorrow","I dont want to"],"correct":0}]}'::jsonb, 100, 30);
