-- ROUND 5: School & Learning
INSERT INTO public.lessons (season, round, order_in_round, type, topic_tag, title_he, content, xp_reward, boots_reward) VALUES

(1, 5, 1, 'words', 'daily_life', 'בית הספר', '{"words":[{"english":"Teacher","hebrew":"מורה","emoji":"👩‍🏫"},{"english":"Book","hebrew":"ספר","emoji":"📚"},{"english":"Pencil","hebrew":"עיפרון","emoji":"✏️"},{"english":"Class","hebrew":"כיתה","emoji":"🏫"},{"english":"Friend","hebrew":"חבר","emoji":"🤝"},{"english":"Learn","hebrew":"ללמוד","emoji":"🧠"},{"english":"Write","hebrew":"לכתוב","emoji":"📝"},{"english":"Read","hebrew":"לקרוא","emoji":"👓"}]}'::jsonb, 65, 14),

(1, 5, 2, 'letters', 'daily_life', 'אותיות K-O', '{"items":[{"letter":"K","word":"King","emoji":"👑","pronunciation":"קֵיי"},{"letter":"L","word":"League","emoji":"🏆","pronunciation":"אֶל"},{"letter":"M","word":"Medal","emoji":"🏅","pronunciation":"אֶם"},{"letter":"N","word":"Number","emoji":"🔢","pronunciation":"אֶן"},{"letter":"O","word":"Orange","emoji":"🍊","pronunciation":"אוֹ"}]}'::jsonb, 65, 14),

(1, 5, 3, 'quiz', 'daily_life', 'חידון בית ספר', '{"questions":[{"question":"How do you say מורה in English?","options":["Student","Teacher","Friend","Book"],"correct":1,"emoji":"👩‍🏫","explanation_he":"Teacher = מורה!"},{"question":"What letter does King start with?","options":["L","M","K","N"],"correct":2,"emoji":"👑","explanation_he":"King מתחיל באות K!"},{"question":"How do you say ספר?","options":["Pencil","Class","Book","Write"],"correct":2,"emoji":"📚","explanation_he":"Book = ספר!"},{"question":"How do you say ללמוד?","options":["Read","Write","Play","Learn"],"correct":3,"emoji":"🧠","explanation_he":"Learn = ללמוד!"},{"question":"What letter does Medal start with?","options":["K","L","N","M"],"correct":3,"emoji":"🏅","explanation_he":"Medal מתחיל באות M!"},{"question":"How do you say חבר?","options":["Teacher","Enemy","Friend","Class"],"correct":2,"emoji":"🤝","explanation_he":"Friend = חבר!"},{"question":"What do you use to write?","options":["Book","Pencil","Teacher","Class"],"correct":1,"emoji":"✏️","explanation_he":"Pencil = עיפרון!"},{"question":"How do you say לקרוא?","options":["Write","Run","Read","Speak"],"correct":2,"emoji":"👓","explanation_he":"Read = לקרוא!"}],"timer_seconds":25,"speed_bonus":true}'::jsonb, 80, 20),

(1, 5, 4, 'spelling', 'daily_life', 'כתיב בית ספר', '{"spelling_items":[{"word":"BOOK","hebrew":"ספר","hint":"4 אותיות, מתחיל ב-B","emoji":"📚"},{"word":"READ","hebrew":"לקרוא","hint":"4 אותיות, מתחיל ב-R","emoji":"👓"},{"word":"KING","hebrew":"מלך","hint":"4 אותיות, מסתיים ב-G","emoji":"👑"},{"word":"LEARN","hebrew":"ללמוד","hint":"5 אותיות","emoji":"🧠"},{"word":"WRITE","hebrew":"לכתוב","hint":"מתחיל ב-W","emoji":"📝"},{"word":"CLASS","hebrew":"כיתה","hint":"מתחיל ב-C","emoji":"🏫"}]}'::jsonb, 80, 20),

-- ROUND 6: Food & Drinks
(1, 6, 1, 'words', 'daily_life', 'אוכל וטעים!', '{"words":[{"english":"Bread","hebrew":"לחם","emoji":"🍞"},{"english":"Water","hebrew":"מים","emoji":"💧"},{"english":"Apple","hebrew":"תפוח","emoji":"🍎"},{"english":"Milk","hebrew":"חלב","emoji":"🥛"},{"english":"Egg","hebrew":"ביצה","emoji":"🥚"},{"english":"Pizza","hebrew":"פיצה","emoji":"🍕"},{"english":"Cake","hebrew":"עוגה","emoji":"🎂"},{"english":"Banana","hebrew":"בננה","emoji":"🍌"}]}'::jsonb, 65, 14),

(1, 6, 2, 'picture_match', 'daily_life', 'התאם אוכל!', '{"picture_items":[{"word":"Bread","hebrew":"לחם","emoji":"🍞"},{"word":"Apple","hebrew":"תפוח","emoji":"🍎"},{"word":"Milk","hebrew":"חלב","emoji":"🥛"},{"word":"Pizza","hebrew":"פיצה","emoji":"🍕"},{"word":"Cake","hebrew":"עוגה","emoji":"🎂"},{"word":"Banana","hebrew":"בננה","emoji":"🍌"},{"word":"Egg","hebrew":"ביצה","emoji":"🥚"},{"word":"Water","hebrew":"מים","emoji":"💧"}]}'::jsonb, 65, 14),

(1, 6, 3, 'quiz', 'daily_life', 'חידון אוכל', '{"questions":[{"question":"How do you say לחם in English?","options":["Cake","Bread","Milk","Egg"],"correct":1,"emoji":"🍞","explanation_he":"Bread = לחם!"},{"question":"What do you drink when thirsty?","options":["Cake","Pizza","Water","Bread"],"correct":2,"emoji":"💧","explanation_he":"Water = מים!"},{"question":"How do you say תפוח?","options":["Banana","Orange","Apple","Egg"],"correct":2,"emoji":"🍎","explanation_he":"Apple = תפוח!"},{"question":"Which comes from a cow?","options":["Egg","Bread","Banana","Milk"],"correct":3,"emoji":"🥛","explanation_he":"Milk = חלב — בא מפרה!"},{"question":"How do you say עוגה?","options":["Pizza","Bread","Cake","Egg"],"correct":2,"emoji":"🎂","explanation_he":"Cake = עוגה!"},{"question":"Which is yellow and long?","options":["Apple","Banana","Egg","Pizza"],"correct":1,"emoji":"🍌","explanation_he":"Banana = בננה — צהובה וארוכה!"},{"question":"How do you say ביצה?","options":["Milk","Bread","Apple","Egg"],"correct":3,"emoji":"🥚","explanation_he":"Egg = ביצה!"},{"question":"How do you say פיצה?","options":["Cake","Bread","Pizza","Banana"],"correct":2,"emoji":"🍕","explanation_he":"Pizza = פיצה — אותו דבר כמעט!"}],"timer_seconds":25,"speed_bonus":false}'::jsonb, 80, 20),

(1, 6, 4, 'sentence_builder', 'daily_life', 'משפטי אוכל', '{"sentence_items":[{"sentence":"I eat an apple every day","hebrew":"אני אוכל תפוח כל יום","words":["I","eat","an","apple","every","day","run","blue"],"emoji":"🍎"},{"sentence":"I drink milk in the morning","hebrew":"אני שותה חלב בבוקר","words":["I","drink","milk","in","the","morning","dog","red"],"emoji":"🥛"},{"sentence":"The cake is very sweet","hebrew":"העוגה מאוד מתוקה","words":["The","cake","is","very","sweet","fish","green"],"emoji":"🎂"},{"sentence":"I love pizza and bread","hebrew":"אני אוהב פיצה ולחם","words":["I","love","pizza","and","bread","bird","yellow"],"emoji":"🍕"}]}'::jsonb, 80, 20),

-- ROUND 7: Advanced Football
(1, 7, 1, 'words', 'football', 'עמדות בכדורגל', '{"words":[{"english":"Goalkeeper","hebrew":"שוער","emoji":"🧤"},{"english":"Defender","hebrew":"בלם","emoji":"🛡️"},{"english":"Midfielder","hebrew":"קשר","emoji":"🔄"},{"english":"Striker","hebrew":"חלוץ","emoji":"⚡"},{"english":"Referee","hebrew":"שופט","emoji":"🟨"},{"english":"Captain","hebrew":"קפטן","emoji":"🏅"},{"english":"Score","hebrew":"לכבוש","emoji":"🎯"},{"english":"Penalty","hebrew":"פנדל","emoji":"⚽"}]}'::jsonb, 75, 18),

(1, 7, 2, 'listening', 'football', 'שמע וזהה — כדורגל', '{"listening_items":[{"text":"The goalkeeper saves the ball!","hebrew":"השוער מציל את הכדור!","options":["The goalkeeper saves","The striker scores","The referee stops","The captain runs"],"correct":0,"emoji":"🧤"},{"text":"The striker scores a goal!","hebrew":"החלוץ כובש שער!","options":["The defender blocks","The striker scores a goal","The midfielder passes","The referee whistles"],"correct":1,"emoji":"⚡"},{"text":"The referee shows a yellow card","hebrew":"השופט מציג כרטיס צהוב","options":["The captain protests","The referee shows a yellow card","The player falls","The team wins"],"correct":1,"emoji":"🟨"},{"text":"The captain leads the team","hebrew":"הקפטן מוביל את הקבוצה","options":["The captain leads the team","The striker runs fast","The defender kicks","The goalkeeper jumps"],"correct":0,"emoji":"🏅"}],"timer_seconds":30}'::jsonb, 75, 18),

(1, 7, 3, 'quiz', 'football', 'חידון כדורגל מתקדם', '{"questions":[{"question":"Who protects the goal?","options":["Striker","Midfielder","Goalkeeper","Referee"],"correct":2,"emoji":"🧤","explanation_he":"Goalkeeper = שוער — מגן על השער!"},{"question":"How do you say חלוץ?","options":["Defender","Goalkeeper","Referee","Striker"],"correct":3,"emoji":"⚡","explanation_he":"Striker = חלוץ — הוא כובש שערים!"},{"question":"How do you say שופט?","options":["Captain","Referee","Midfielder","Player"],"correct":1,"emoji":"🟨","explanation_he":"Referee = שופט!"},{"question":"What is a penalty?","options":["A yellow card","A free kick from the spot","A corner kick","A throw-in"],"correct":1,"emoji":"⚽","explanation_he":"Penalty = פנדל — בעיטה ממרחק קבוע!"},{"question":"How do you say קפטן?","options":["Coach","Referee","Captain","Striker"],"correct":2,"emoji":"🏅","explanation_he":"Captain = קפטן — מנהיג הקבוצה!"},{"question":"What does Midfielder mean?","options":["שוער","חלוץ","בלם","קשר"],"correct":3,"emoji":"🔄","explanation_he":"Midfielder = קשר — משחק באמצע!"},{"question":"How do you say לכבוש שער?","options":["Pass the ball","Score a goal","Save the ball","Stop the game"],"correct":1,"emoji":"🎯","explanation_he":"Score a goal = לכבוש שער!"},{"question":"Who wears gloves in football?","options":["Striker","Referee","Midfielder","Goalkeeper"],"correct":3,"emoji":"🧤","explanation_he":"The Goalkeeper = השוער לובש כפפות!"},{"question":"How do you say בלם?","options":["Midfielder","Striker","Goalkeeper","Defender"],"correct":3,"emoji":"🛡️","explanation_he":"Defender = בלם — עוצר את החלוצים!"},{"question":"What color card means you are out?","options":["Yellow","Green","Blue","Red"],"correct":3,"emoji":"🟥","explanation_he":"Red card = כרטיס אדום — יוצאים מהמגרש!"}],"timer_seconds":20,"speed_bonus":true}'::jsonb, 90, 25),

(1, 7, 4, 'conversation', 'football', 'ביום המשחק', '{"dialogue":[{"speaker":"coach","text":"Today we play the final! Are you ready?","hebrew":"היום אנחנו משחקים גמר! אתה מוכן?","emoji":"🏆"},{"speaker":"child","hebrew":"כן! אני מוכן לגמר!","options":["Yes! I am ready for the final!","No, I am tired","I want to go home"],"correct":0},{"speaker":"coach","text":"You are our striker today. Score a goal!","hebrew":"אתה החלוץ שלנו היום. כבוש שער!","emoji":"⚡"},{"speaker":"child","hebrew":"אכבוש שער בשביל הקבוצה!","options":["I will score for the team!","I prefer to defend","I am scared"],"correct":0},{"speaker":"coach","text":"The referee blows the whistle. The game starts!","hebrew":"השופט שורק. המשחק מתחיל!","emoji":"🟨"},{"speaker":"child","hebrew":"בוא נצא לנצח!","options":["Let us go and win!","Wait a moment","I need water"],"correct":0},{"speaker":"coach","text":"GOAL! You scored! We are champions!","hebrew":"שער! כבשת! אנחנו אלופים!","emoji":"🏆"},{"speaker":"child","hebrew":"אנחנו ניצחנו! אנחנו הכי טובים!","options":["We won! We are the best!","Lucky shot","The referee helped us"],"correct":0}]}'::jsonb, 90, 25),

-- ROUND 8: Feelings & Daily Life
(1, 8, 1, 'words', 'daily_life', 'רגשות ומצבים', '{"words":[{"english":"Happy","hebrew":"שמח","emoji":"😊"},{"english":"Sad","hebrew":"עצוב","emoji":"😢"},{"english":"Angry","hebrew":"כועס","emoji":"😠"},{"english":"Tired","hebrew":"עייף","emoji":"😴"},{"english":"Hungry","hebrew":"רעב","emoji":"🤤"},{"english":"Scared","hebrew":"מפחד","emoji":"😨"},{"english":"Surprised","hebrew":"מופתע","emoji":"😲"},{"english":"Proud","hebrew":"גאה","emoji":"🦁"}]}'::jsonb, 70, 16),

(1, 8, 2, 'picture_match', 'daily_life', 'התאם רגשות!', '{"picture_items":[{"word":"Happy","hebrew":"שמח","emoji":"😊"},{"word":"Sad","hebrew":"עצוב","emoji":"😢"},{"word":"Angry","hebrew":"כועס","emoji":"😠"},{"word":"Tired","hebrew":"עייף","emoji":"😴"},{"word":"Hungry","hebrew":"רעב","emoji":"🤤"},{"word":"Scared","hebrew":"מפחד","emoji":"😨"},{"word":"Surprised","hebrew":"מופתע","emoji":"😲"},{"word":"Proud","hebrew":"גאה","emoji":"🦁"}]}'::jsonb, 70, 16),

(1, 8, 3, 'quiz', 'daily_life', 'חידון רגשות ויומיום', '{"questions":[{"question":"How do you say שמח in English?","options":["Sad","Angry","Happy","Tired"],"correct":2,"emoji":"😊","explanation_he":"Happy = שמח!"},{"question":"You did not sleep — how do you feel?","options":["Happy","Hungry","Scared","Tired"],"correct":3,"emoji":"😴","explanation_he":"Tired = עייף — לא ישנת מספיק!"},{"question":"How do you say כועס?","options":["Happy","Sad","Proud","Angry"],"correct":3,"emoji":"😠","explanation_he":"Angry = כועס!"},{"question":"You did not eat all day — how do you feel?","options":["Proud","Hungry","Happy","Surprised"],"correct":1,"emoji":"🤤","explanation_he":"Hungry = רעב!"},{"question":"How do you say גאה?","options":["Scared","Tired","Proud","Angry"],"correct":2,"emoji":"🦁","explanation_he":"Proud = גאה — כשעושים משהו טוב!"},{"question":"Something scary happens — how do you feel?","options":["Happy","Proud","Scared","Surprised"],"correct":2,"emoji":"😨","explanation_he":"Scared = מפחד!"},{"question":"How do you say עצוב?","options":["Angry","Sad","Tired","Hungry"],"correct":1,"emoji":"😢","explanation_he":"Sad = עצוב!"},{"question":"A surprise party for you — how do you feel?","options":["Angry","Tired","Sad","Surprised"],"correct":3,"emoji":"😲","explanation_he":"Surprised = מופתע!"},{"question":"You won the championship — how do you feel?","options":["Sad","Scared","Tired","Proud"],"correct":3,"emoji":"🏆","explanation_he":"Proud = גאה — כמו שאנחנו גאים בך!"},{"question":"Your best friend moved away — how do you feel?","options":["Happy","Surprised","Sad","Angry"],"correct":2,"emoji":"😢","explanation_he":"Sad = עצוב — זה בסדר להרגיש ככה!"}],"timer_seconds":25,"speed_bonus":false}'::jsonb, 100, 30),

(1, 8, 4, 'conversation', 'daily_life', 'איך אתה מרגיש?', '{"dialogue":[{"speaker":"coach","text":"Hey! How are you feeling today?","hebrew":"היי! איך אתה מרגיש היום?","emoji":"😊"},{"speaker":"child","hebrew":"אני מרגיש מצוין!","options":["I am feeling great!","I am sad","I do not know"],"correct":0},{"speaker":"coach","text":"Are you happy to be here?","hebrew":"אתה שמח להיות כאן?","emoji":"😊"},{"speaker":"child","hebrew":"כן! אני מאוד שמח!","options":["Yes! I am very happy!","No, I am tired","I am hungry"],"correct":0},{"speaker":"coach","text":"Are you tired from the lesson?","hebrew":"אתה עייף מהשיעור?","emoji":"😴"},{"speaker":"child","hebrew":"לא! אני מוכן לעוד!","options":["No! I am ready for more!","Yes, I want to sleep","A little bit"],"correct":0},{"speaker":"coach","text":"Are you proud of what you learned?","hebrew":"אתה גאה במה שלמדת?","emoji":"🦁"},{"speaker":"child","hebrew":"כן! אני גאה מאוד!","options":["Yes! I am very proud!","Not really","I forgot everything"],"correct":0}]}'::jsonb, 100, 30)

ON CONFLICT DO NOTHING;
